import type { RequestHandler } from "msw";
import { autoGeneratedHandlers } from "./mocker";
import { platformHandlers } from "./platform-handlers";
import { registryListHandlers } from "./registry-list";
import { serverDetailHandlers } from "./server-detail";

// Scenarios are now handled via the x-mock-scenario header in AutoAPIMock.generatedHandler
// See src/mocks/scenarioNames.ts for available scenarios

export const handlers: RequestHandler[] = [
  ...serverDetailHandlers,
  ...registryListHandlers, // 覆盖 registry 列表，实现真实分页
  ...autoGeneratedHandlers,
  ...platformHandlers,
];
